name: Data Synchronization

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone OpenFlights repository
        run: |
          git clone https://github.com/jpatokal/openflights.git openflights

      - name: Compare data files
        id: compare
        run: |
          set -e
          diff -q openflights/data/airports.dat airports.csv || echo "airports.csv is outdated"
          diff -q openflights/data/airlines.dat airlines.csv || echo "airlines.csv is outdated"
          echo "::set-output name=update_airports::$(diff -q openflights/data/airports.dat airports.csv > /dev/null; echo $?)"
          echo "::set-output name=update_airlines::$(diff -q openflights/data/airlines.dat airlines.csv > /dev/null; echo $?)"

      - name: Update airports.csv
        if: ${{ steps.compare.outputs.update_airports != '0' }}
        run: |
          cp openflights/data/airports.dat airports.csv
          git add airports.csv
          git commit -m "Update airports.csv from OpenFlights"

      - name: Update airlines.csv
        if: ${{ steps.compare.outputs.update_airlines != '0' }}
        run: |
          cp openflights/data/airlines.dat airlines.csv
          git add airlines.csv
          git commit -m "Update airlines.csv from OpenFlights"

      - name: Push changes
        if: ${{ steps.compare.outputs.update_airports != '0' || steps.compare.outputs.update_airlines != '0' }}
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

  process-data:
    needs: sync-data
    if: ${{ needs.steps.compare.outputs.update_airports != '0' || needs.steps.compare.outputs.update_airlines != '0' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download executable artifact
        uses: actions/download-artifact@v3
        with:
          name: executable
          path: .

      - name: Make the executable runnable
        run: chmod +x ./phase-nomad-data

      - name: Run executable and update .sqlite
        run: |
          ./phase-nomad-data
          git add *.sqlite
          git commit -m "Update SQLite database"

      - name: Push SQLite changes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
